const PHRASE_KEYS = Object.freeze({
  'WEYLAND-YUTANI': 'WY_TERMINAL.phrases.weylandYutani',
  '"BUILDING BETTER WORLDS"': 'WY_TERMINAL.phrases.buildingBetterWorlds',
  'INTERFACE 2037 — SHIPBOARD TERMINAL v3.1.7': 'WY_TERMINAL.phrases.interfaceLabel',
  'PERFORMING SYSTEM DIAGNOSTICS...': 'WY_TERMINAL.phrases.performingDiagnostics',
  '— SELECT TERMINAL FUNCTION': 'WY_TERMINAL.phrases.selectTerminalFunction',
  'SYSTEM:': 'WY_TERMINAL.phrases.systemLabel',
  'SHIP': 'WY_TERMINAL.phrases.ship',
  'NAV': 'WY_TERMINAL.phrases.nav',
  'TACTICAL': 'WY_TERMINAL.phrases.tactical',
  'COMMS': 'WY_TERMINAL.phrases.comms',
  'CARGO': 'WY_TERMINAL.phrases.cargo',
  'DISPLAY': 'WY_TERMINAL.phrases.display',
  'STATUS': 'WY_TERMINAL.status.status',
  'CREW': 'WY_TERMINAL.buttons.crew',
  'SHIP OPS': 'WY_TERMINAL.buttons.shipOps',
  'LOGS': 'WY_TERMINAL.buttons.logs',
  'SYSTEMS': 'WY_TERMINAL.buttons.systems',
  'GAME CLOCK': 'WY_TERMINAL.buttons.gameClock',
  'TIMERS': 'WY_TERMINAL.buttons.timers',
  'EMERGENCY': 'WY_TERMINAL.buttons.emergency',
  'MU/TH/UR': 'WY_TERMINAL.buttons.muthur',
  'SCHEMATICS': 'WY_TERMINAL.buttons.schematics',
  'CMD CODE': 'WY_TERMINAL.buttons.commandCode',
  'GM CONTROLS': 'WY_TERMINAL.buttons.gmControls',
  'USER:': 'WY_TERMINAL.phrases.userLabel',
  'CLEARANCE:': 'WY_TERMINAL.phrases.clearanceLabel',
  'MEM: OK': 'WY_TERMINAL.phrases.memOk',
  'LINKED': 'WY_TERMINAL.phrases.linked',
  'STANDBY': 'WY_TERMINAL.phrases.standby',
  'ONLINE': 'WY_TERMINAL.status.online',
  'OFFLINE': 'WY_TERMINAL.status.offline',
  'NOMINAL': 'WY_TERMINAL.status.nominal',
  'WARNING': 'WY_TERMINAL.status.warning',
  'CRITICAL': 'WY_TERMINAL.status.critical',
  'UNKNOWN': 'WY_TERMINAL.status.unknown',
  'ACTIVE': 'WY_TERMINAL.status.active',
  'INACTIVE': 'WY_TERMINAL.status.inactive',
  'SYSTEM': 'WY_TERMINAL.phrases.system',
  'POWER': 'WY_TERMINAL.phrases.power',
  'POWER %': 'WY_TERMINAL.phrases.powerPercent',
  'NOTES': 'WY_TERMINAL.phrases.notes',
  'NAME': 'WY_TERMINAL.phrases.name',
  'ROLE': 'WY_TERMINAL.phrases.role',
  'LOCATION': 'WY_TERMINAL.phrases.location',
  'DATE': 'WY_TERMINAL.phrases.date',
  'SENDER': 'WY_TERMINAL.phrases.sender',
  'SUBJECT': 'WY_TERMINAL.phrases.subject',
  'LEVEL': 'WY_TERMINAL.phrases.level',
  'CLASSIFICATION': 'WY_TERMINAL.phrases.classification',
  'MEDIA': 'WY_TERMINAL.phrases.media',
  'DETAIL': 'WY_TERMINAL.phrases.detail',
  'TYPE': 'WY_TERMINAL.phrases.type',
  'TERRITORY': 'WY_TERMINAL.phrases.territory',
  'SECTOR': 'WY_TERMINAL.phrases.sector',
  'COORDINATES': 'WY_TERMINAL.phrases.coordinates',
  'AFFILIATION': 'WY_TERMINAL.phrases.affiliation',
  'DESCRIPTION': 'WY_TERMINAL.phrases.description',
  'DESIGNATION': 'WY_TERMINAL.phrases.designation',
  'DISTANCE': 'WY_TERMINAL.phrases.distance',
  'ITEM': 'WY_TERMINAL.phrases.item',
  'QTY': 'WY_TERMINAL.phrases.quantityShort',
  'QUANTITY': 'WY_TERMINAL.phrases.quantity',
  'CATEGORY': 'WY_TERMINAL.phrases.category',
  'AMMUNITION': 'WY_TERMINAL.phrases.ammunition',
  'WEAPON': 'WY_TERMINAL.phrases.weapon',
  'FACILITY': 'WY_TERMINAL.phrases.facility',
  'ASSIGNMENT': 'WY_TERMINAL.phrases.assignment',
  'UNIT': 'WY_TERMINAL.phrases.unit',
  'CONTAINMENT': 'WY_TERMINAL.phrases.containment',
  'BIO-HAZARD': 'WY_TERMINAL.phrases.bioHazard',
  'CONTENTS': 'WY_TERMINAL.phrases.contents',
  'SAVE': 'WY_TERMINAL.actions.save',
  'CLOSE': 'WY_TERMINAL.actions.close',
  '[CLOSE]': 'WY_TERMINAL.actions.closeBracketed',
  '[EDIT]': 'WY_TERMINAL.actions.editBracketed',
  '[DEL]': 'WY_TERMINAL.actions.deleteBracketed',
  '[VIEW]': 'WY_TERMINAL.actions.viewBracketed',
  'CANCEL': 'WY_TERMINAL.actions.cancel',
  'COMMIT': 'WY_TERMINAL.actions.commit',
  'EDIT': 'WY_TERMINAL.actions.edit',
  'DEL': 'WY_TERMINAL.actions.deleteShort',
  'DELETE': 'WY_TERMINAL.actions.delete',
  'CLR': 'WY_TERMINAL.actions.clearShort',
  'ENT': 'WY_TERMINAL.actions.enterShort',
  'SEND': 'WY_TERMINAL.actions.send',
  'SPACE': 'WY_TERMINAL.actions.space',
  'BACKSPACE': 'WY_TERMINAL.actions.backspace',
  'SAVE CONFIGURATION': 'WY_TERMINAL.actions.saveConfiguration',
  'SAVE PLAYER EFFECTS': 'WY_TERMINAL.actions.savePlayerEffects',
  'RELOAD STATUS': 'WY_TERMINAL.actions.reloadStatus',
  'CLEAR CHAT LOG': 'WY_TERMINAL.actions.clearChatLog',
  'SAVE NAVIGATION DATA': 'WY_TERMINAL.actions.saveNavigationData',
  'SAVE ALL': 'WY_TERMINAL.actions.saveAll',
  'REGENERATE ALL CODES': 'WY_TERMINAL.actions.regenerateAllCodes',
  'CREATE EVENT TIMER': 'WY_TERMINAL.actions.createEventTimer',
  'CLEAR ALL COMPLETED': 'WY_TERMINAL.actions.clearAllCompleted',
  'CLEAR ALL CANCELLED': 'WY_TERMINAL.actions.clearAllCancelled',
  'SAVE CHANGES': 'WY_TERMINAL.actions.saveChanges',
  'DISCARD': 'WY_TERMINAL.actions.discard',
  '+ ADD ITEM': 'WY_TERMINAL.actions.addItem',
  '+ NEW SYSTEM': 'WY_TERMINAL.actions.newSystem',
  'START CLOCK': 'WY_TERMINAL.actions.startClock',
  'STOP CLOCK': 'WY_TERMINAL.actions.stopClock',
  'RESET TO DEFAULT': 'WY_TERMINAL.actions.resetToDefault',
  'SET FREQUENCY': 'WY_TERMINAL.actions.setFrequency',
  'COMMIT LOG': 'WY_TERMINAL.actions.commitLog',
  'PLACE MARKER': 'WY_TERMINAL.actions.placeMarker',
  'SAVE MARKER': 'WY_TERMINAL.actions.saveMarker',
  'PUSH TO PLAYERS': 'WY_TERMINAL.actions.pushToPlayers',
  'SYNC TOKENS': 'WY_TERMINAL.actions.syncTokens',
  'OPTIMIZE FOUNDRYVTT SETTINGS': 'WY_TERMINAL.actions.optimizeFoundry',
  'TERMINAL CONFIGURATION': 'WY_TERMINAL.sections.terminalConfiguration',
  'ACTIVE SHIP PROFILE': 'WY_TERMINAL.sections.activeShipProfile',
  'PLAYER TERMINAL EFFECTS': 'WY_TERMINAL.sections.playerTerminalEffects',
  'MU/TH/UR AI ENGINE': 'WY_TERMINAL.sections.muthurAiEngine',
  'FOUNDRYVTT OPTIMIZATION': 'WY_TERMINAL.sections.foundryOptimization',
  'RESET GAME SETTINGS': 'WY_TERMINAL.sections.resetGameSettings',
  'PLAYER SCHEMATIC ACCESS': 'WY_TERMINAL.sections.playerSchematicAccess',
  'CREW MANIFEST FOLDERS': 'WY_TERMINAL.sections.crewManifestFolders',
  'NAVIGATION': 'WY_TERMINAL.sections.navigation',
  'CREW MANIFEST': 'WY_TERMINAL.sections.crewManifest',
  'SHIP SYSTEMS DIAGNOSTIC': 'WY_TERMINAL.sections.shipSystemsDiagnostic',
  'SYSTEM OVERVIEW': 'WY_TERMINAL.sections.systemOverview',
  'COMMUNICATIONS ARRAY': 'WY_TERMINAL.sections.communicationsArray',
  'RECEIVED TRANSMISSIONS': 'WY_TERMINAL.sections.receivedTransmissions',
  'GAME TIME CONTROL': 'WY_TERMINAL.sections.gameTimeControl',
  'ADJUST GAME CLOCK': 'WY_TERMINAL.sections.adjustGameClock',
  'ACTIVE TIMERS': 'WY_TERMINAL.sections.activeTimers',
  'CREATE NEW TIMER': 'WY_TERMINAL.sections.createNewTimer',
  'COMPLETED': 'WY_TERMINAL.sections.completed',
  'CANCELLED': 'WY_TERMINAL.sections.cancelled',
  'COMMAND CODE AUTHORIZATION': 'WY_TERMINAL.sections.commandCodeAuthorization',
  'CURRENT CLEARANCE LEVEL': 'WY_TERMINAL.sections.currentClearanceLevel',
  'SHIP SCHEMATIC ACCESS': 'WY_TERMINAL.sections.shipSchematicAccess',
  'SELECT A SCENE TO DISPLAY': 'WY_TERMINAL.sections.selectSceneToDisplay',
  'SPECIMEN CONTAINMENT': 'WY_TERMINAL.sections.specimenContainment',
  'ENVIRONMENTAL MONITORS': 'WY_TERMINAL.sections.environmentalMonitors',
  'TARGETING SYSTEM': 'WY_TERMINAL.sections.targetingSystem',
  'POWER DISTRIBUTION': 'WY_TERMINAL.sections.powerDistribution',
  'ACTIVE TASKS': 'WY_TERMINAL.sections.activeTasks',
  'ATTRIBUTES': 'WY_TERMINAL.sections.attributes',
  'SKILLS': 'WY_TERMINAL.sections.skills',
  'PERSONNEL FILE': 'WY_TERMINAL.sections.personnelFile',
  'ADD CARGO ITEM': 'WY_TERMINAL.sections.addCargoItem',
  'CREATE NEW STAR SYSTEM': 'WY_TERMINAL.sections.createNewStarSystem',
  'ENTER COMMAND CODE': 'WY_TERMINAL.sections.enterCommandCode',
  'AUTHORIZATION REQUIRED FOR CLASSIFIED ACCESS': 'WY_TERMINAL.sections.authorizationRequired',
  'NO ACTIVE TIMERS': 'WY_TERMINAL.sections.noActiveTimers',
  'NO ADDITIONAL PERSONNEL DATA ON FILE.': 'WY_TERMINAL.sections.noPersonnelData',
  'OFF': 'WY_TERMINAL.options.off',
  'LIGHT': 'WY_TERMINAL.options.light',
  'MEDIUM': 'WY_TERMINAL.options.medium',
  'HEAVY': 'WY_TERMINAL.options.heavy',
  'NORMAL': 'WY_TERMINAL.options.normal',
  'UNCLASSIFIED': 'WY_TERMINAL.options.unclassified',
  'PERSONAL': 'WY_TERMINAL.options.personal',
  'MEDICAL': 'WY_TERMINAL.options.medical',
  'CONFIDENTIAL': 'WY_TERMINAL.options.confidential',
  'SENSITIVE': 'WY_TERMINAL.options.sensitive',
  'RESTRICTED': 'WY_TERMINAL.options.restricted',
  'CORPORATE': 'WY_TERMINAL.options.corporate',
  'TEXT': 'WY_TERMINAL.options.text',
  'IMAGE': 'WY_TERMINAL.options.image',
  'VIDEO': 'WY_TERMINAL.options.video',
  'AUDIO (MP3/WAV)': 'WY_TERMINAL.options.audio',
  'CARGO': 'WY_TERMINAL.options.cargo',
  'EQUIPMENT': 'WY_TERMINAL.options.equipment',
  'SUPPLIES': 'WY_TERMINAL.options.supplies',
  'TOOL': 'WY_TERMINAL.options.tool',
  'VEHICLE': 'WY_TERMINAL.options.vehicle',
  'HAZMAT': 'WY_TERMINAL.options.hazmat',
  'SYSTEM': 'WY_TERMINAL.options.system',
  'BINARY': 'WY_TERMINAL.options.binary',
  'TRINARY': 'WY_TERMINAL.options.trinary',
  'NEBULA': 'WY_TERMINAL.options.nebula',
  'ANOMALY': 'WY_TERMINAL.options.anomaly',
  'SURVEYED': 'WY_TERMINAL.options.surveyed',
  'UNEXPLORED': 'WY_TERMINAL.options.unexplored',
  'REBUILDING': 'WY_TERMINAL.options.rebuilding',
  'RECONTACTED': 'WY_TERMINAL.options.recontacted',
  'QUARANTINE': 'WY_TERMINAL.options.quarantine',
  'ABANDONED': 'WY_TERMINAL.options.abandoned',
  'DECOMMISSIONED': 'WY_TERMINAL.options.decommissioned',
  'CLASSIFIED': 'WY_TERMINAL.options.classified',
  'CUSTOM': 'WY_TERMINAL.options.custom',
  'NAVIGATION': 'WY_TERMINAL.options.navigation',
  'LOG ENTRY ONLY': 'WY_TERMINAL.options.logEntryOnly',
  'SET SYSTEM STATE': 'WY_TERMINAL.options.setSystemState',
  'ON DUTY': 'WY_TERMINAL.options.onDuty',
  'OFF DUTY': 'WY_TERMINAL.options.offDuty',
  'RESTING': 'WY_TERMINAL.options.resting',
  'IN CRYO': 'WY_TERMINAL.options.inCryo',
  'INJURED': 'WY_TERMINAL.options.injured',
  'MIA': 'WY_TERMINAL.options.mia',
  'KIA': 'WY_TERMINAL.options.kia',
  'QUARANTINED': 'WY_TERMINAL.options.quarantined',
  'DETAINED': 'WY_TERMINAL.options.detained',
  'UNASSIGNED': 'WY_TERMINAL.options.unassigned',
  'CREWMEMBER': 'WY_TERMINAL.options.crewmember',
  'NONE': 'WY_TERMINAL.options.none',
  'CAPTAIN': 'WY_TERMINAL.options.captain',
  'MASTER OVERRIDE': 'WY_TERMINAL.options.masterOverride',
  'YEAR': 'WY_TERMINAL.units.year',
  'MONTH': 'WY_TERMINAL.units.month',
  'DAY': 'WY_TERMINAL.units.day',
  'HOUR': 'WY_TERMINAL.units.hour',
  'MIN': 'WY_TERMINAL.units.minute',
  'Zoom In': 'WY_TERMINAL.messages.zoomIn',
  'Zoom Out': 'WY_TERMINAL.messages.zoomOut',
  'Reset View': 'WY_TERMINAL.messages.resetView',
  'STELLAR CARTOGRAPHY': 'WY_TERMINAL.sections.stellarCartography',
  'TASK': 'WY_TERMINAL.phrases.task',
  'ETA': 'WY_TERMINAL.phrases.eta',
  'ROLE:': 'WY_TERMINAL.phrases.roleColon',
  'LOCATION:': 'WY_TERMINAL.phrases.locationColon',
  'STATUS:': 'WY_TERMINAL.phrases.statusColon',
  'SHIP:': 'WY_TERMINAL.phrases.shipColon',
  'HEALTH:': 'WY_TERMINAL.phrases.healthColon',
  'STRESS:': 'WY_TERMINAL.phrases.stressColon',
  'RADIATION:': 'WY_TERMINAL.phrases.radiationColon',
  'COMM STATUS:': 'WY_TERMINAL.phrases.commStatusColon',
  'FREQUENCY:': 'WY_TERMINAL.phrases.frequencyColon',
  'RANGE:': 'WY_TERMINAL.phrases.rangeColon',
  'VESSEL:': 'WY_TERMINAL.phrases.vesselColon',
  'CLASS:': 'WY_TERMINAL.phrases.classColon',
  'REGISTRY:': 'WY_TERMINAL.phrases.registryColon',
  'OWNER:': 'WY_TERMINAL.phrases.ownerColon',
  'WEYLAND-YUTANI CORP.': 'WY_TERMINAL.phrases.weylandYutaniCorp',
  'ITEM NAME': 'WY_TERMINAL.phrases.itemName',
  'NEW DURATION': 'WY_TERMINAL.phrases.newDuration',
  'DURATION': 'WY_TERMINAL.phrases.duration',
  'LABEL': 'WY_TERMINAL.phrases.label',
  'ON COMPLETE': 'WY_TERMINAL.phrases.onComplete',
  'SET STATE': 'WY_TERMINAL.phrases.setState',
  'CLEARANCE': 'WY_TERMINAL.phrases.clearance',
  'CODE ROLE': 'WY_TERMINAL.phrases.codeRole',
  'CMD CODE': 'WY_TERMINAL.phrases.commandCode',
  'SHIP ASSIGNMENT': 'WY_TERMINAL.phrases.shipAssignment',
  'STR': 'WY_TERMINAL.attributes.str',
  'AGL': 'WY_TERMINAL.attributes.agl',
  'WIT': 'WY_TERMINAL.attributes.wit',
  'EMP': 'WY_TERMINAL.attributes.emp',
  'STRENGTH': 'WY_TERMINAL.attributes.strength',
  'AGILITY': 'WY_TERMINAL.attributes.agility',
  'WITS': 'WY_TERMINAL.attributes.wits',
  'EMPATHY': 'WY_TERMINAL.attributes.empathy',
  'HEAVY MACHINERY': 'WY_TERMINAL.skills.heavyMachinery',
  'CLOSE COMBAT': 'WY_TERMINAL.skills.closeCombat',
  'STAMINA': 'WY_TERMINAL.skills.stamina',
  'RANGED COMBAT': 'WY_TERMINAL.skills.rangedCombat',
  'MOBILITY': 'WY_TERMINAL.skills.mobility',
  'PILOTING': 'WY_TERMINAL.skills.piloting',
  'OBSERVATION': 'WY_TERMINAL.skills.observation',
  'COMTECH': 'WY_TERMINAL.skills.comtech',
  'SURVIVAL': 'WY_TERMINAL.skills.survival',
  'COMMAND': 'WY_TERMINAL.skills.command',
  'MANIPULATION': 'WY_TERMINAL.skills.manipulation',
  'MEDICAL AID': 'WY_TERMINAL.skills.medicalAid',
  'NAVIGATION — STELLAR CARTOGRAPHY': 'WY_TERMINAL.sections.navigationStellarCartography',
  'STELLAR NAVIGATION CHART': 'WY_TERMINAL.sections.stellarNavigationChart',
  'NEW NAV MARKER': 'WY_TERMINAL.sections.newNavMarker',
  'NAV MARKERS': 'WY_TERMINAL.sections.navMarkers',
  'WAYPOINTS': 'WY_TERMINAL.sections.waypoints',
  'TIME PAUSED': 'WY_TERMINAL.sections.timePaused',
  'TIME ACCELERATION: 10:1': 'WY_TERMINAL.sections.timeAcceleration',
  'CREATE NEW LOG ENTRY': 'WY_TERMINAL.sections.createNewLogEntry',
  '⚠ EMERGENCY PROTOCOLS ⚠': 'WY_TERMINAL.emergency.title',
  'AUTHORIZED PERSONNEL ONLY — ALL ACTIONS LOGGED': 'WY_TERMINAL.emergency.authorizedOnly',
  '⚠ SELF-DESTRUCT SEQUENCE ⚠': 'WY_TERMINAL.emergency.selfDestructSequence',
  'EVACUATION PROTOCOL': 'WY_TERMINAL.emergency.evacuationProtocol',
  'SHIP LOCKDOWN': 'WY_TERMINAL.emergency.shipLockdown',
  'BROADCAST DISTRESS SIGNAL': 'WY_TERMINAL.emergency.broadcastDistress',
  'ATMOSPHERE PURGE — DECK SELECT': 'WY_TERMINAL.emergency.atmospherePurgeDeck',
  'UNKNOWN BIOLOGICAL ORGANISM DETECTED': 'WY_TERMINAL.emergency.unknownBioDetected',
  '⚠ SELF-DESTRUCT ACTIVE ⚠': 'WY_TERMINAL.emergency.selfDestructActive',
  '⚠ SELF-DESTRUCT SEQUENCE ACTIVE ⚠': 'WY_TERMINAL.emergency.selfDestructSequenceActive',
  'ALL PERSONNEL EVACUATE IMMEDIATELY': 'WY_TERMINAL.emergency.evacuateImmediately',
  'ABORT SELF-DESTRUCT': 'WY_TERMINAL.emergency.abortSelfDestruct',
  '⚠ EVACUATION PROTOCOL ACTIVE ⚠': 'WY_TERMINAL.emergency.evacuationActive',
  'ALL PERSONNEL — REPORT TO ESCAPE PODS': 'WY_TERMINAL.emergency.reportToPods',
  'ALL PERSONNEL REPORT TO ESCAPE PODS': 'WY_TERMINAL.emergency.reportToPods',
  'CANCEL EVACUATION': 'WY_TERMINAL.emergency.cancelEvacuation',
  '⚠ SHIP LOCKDOWN ACTIVE ⚠': 'WY_TERMINAL.emergency.lockdownActive',
  '⚠ SHIP LOCKDOWN — ALL DOORS SEALED ⚠': 'WY_TERMINAL.emergency.lockdownSealed',
  'ALL AIRLOCKS AND DOORS SEALED': 'WY_TERMINAL.emergency.airlocksSealed',
  'AIRLOCK AND DOOR CONTROLS DISABLED': 'WY_TERMINAL.emergency.airlockControlsDisabled',
  'LIFT LOCKDOWN': 'WY_TERMINAL.emergency.liftLockdown',
  '⚠ DISTRESS SIGNAL BROADCASTING ⚠': 'WY_TERMINAL.emergency.distressBroadcasting',
  'TRANSMITTING ON ALL FREQUENCIES': 'WY_TERMINAL.emergency.transmittingAllFrequencies',
  'CANCEL BROADCAST': 'WY_TERMINAL.emergency.cancelBroadcast',
  '⚠ ATMOSPHERE PURGE IN PROGRESS ⚠': 'WY_TERMINAL.emergency.atmospherePurgeActive',
  'CANCEL PURGE': 'WY_TERMINAL.emergency.cancelPurge',
  '⚠ UNKNOWN BIOLOGICAL ORGANISM DETECTED ⚠': 'WY_TERMINAL.emergency.unknownBioActive',
  'CANCEL ALERT': 'WY_TERMINAL.emergency.cancelAlert',
  'HEADING:': 'WY_TERMINAL.nav.headingColon',
  'SPEED:': 'WY_TERMINAL.nav.speedColon',
  'FUEL RESERVES:': 'WY_TERMINAL.nav.fuelReservesColon',
  'ETA:': 'WY_TERMINAL.nav.etaColon',
  'ENGINES:': 'WY_TERMINAL.nav.enginesColon',
  'THRUSTERS:': 'WY_TERMINAL.nav.thrustersColon',
  'POSITION:': 'WY_TERMINAL.nav.positionColon',
  'DESTINATION:': 'WY_TERMINAL.nav.destinationColon',
  'DST COORDINATES:': 'WY_TERMINAL.nav.dstCoordinatesColon',
  'WAYPOINT': 'WY_TERMINAL.nav.markerTypes.waypoint',
  'STATION': 'WY_TERMINAL.nav.markerTypes.station',
  'PLANET': 'WY_TERMINAL.nav.markerTypes.planet',
  'HAZARD': 'WY_TERMINAL.nav.markerTypes.hazard',
  'SIGNAL': 'WY_TERMINAL.nav.markerTypes.signal',
  'DEPARTURE': 'WY_TERMINAL.nav.markerTypes.departure',
  'PLAYER': 'WY_TERMINAL.nav.markerTypes.player',
  'PROGRESS': 'WY_TERMINAL.nav.progress',
  'COORDS': 'WY_TERMINAL.nav.coords',
  'EDT': 'WY_TERMINAL.actions.editTiny',
  'STAR MAP': 'WY_TERMINAL.nav.starMap',
  'Click map to place a NAV marker': 'WY_TERMINAL.nav.placeMarkerHint',
  'SHIP NAME': 'WY_TERMINAL.settings.shipName.name',
  'SHIP CLASS': 'WY_TERMINAL.settings.shipClass.name',
  'SHIP REGISTRY': 'WY_TERMINAL.settings.shipRegistry.name',
  'CRT SCANLINES': 'WY_TERMINAL.settings.scanlines.name',
  'CRT FLICKER': 'WY_TERMINAL.settings.crtFlicker.name',
  'SOUND EFFECTS': 'WY_TERMINAL.settings.soundEnabled.name',
  'API BASE URL': 'WY_TERMINAL.settings.openaiBaseUrl.name',
  'API KEY': 'WY_TERMINAL.settings.openaiApiKey.name',
  'AI MODEL': 'WY_TERMINAL.settings.openaiModel.name',
  'SCENARIO PLUGIN': 'WY_TERMINAL.settings.muthurPlugin.name',
  'EXTERNAL SERVER URL': 'WY_TERMINAL.settings.muthurUrl.name',
  'STATUS FILE PATH': 'WY_TERMINAL.settings.statusPath.name',
  'ENTER QUERY...': 'WY_TERMINAL.muthur.enterQuery',
  'MODE:': 'WY_TERMINAL.phrases.modeColon',
  'LOCK:': 'WY_TERMINAL.phrases.lockColon',
  'THREAT LEVEL:': 'WY_TERMINAL.phrases.threatLevelColon',
  'ATMOSPHERE:': 'WY_TERMINAL.phrases.atmosphereColon',
  'BIO-CONTAMINANT:': 'WY_TERMINAL.phrases.bioContaminantColon',
});

const STATIC_UI_SELECTOR = [
  '.wy-boot-logo',
  '.wy-boot-line',
  '.wy-header-title',
  '.wy-header-status-line',
  '.wy-nav-label',
  '.btn-label',
  '.wy-section-title',
  '.wy-section-divider',
  '.wy-setting-label',
  '.wy-nav-starmap-label',
  '.wy-nav-marker-toggle',
  '.wy-log-form-label',
  '.wy-ss-form-label',
  '.wy-ss-filter-label',
  '.wy-user-field-label',
  '.wy-crew-gm-label',
  '.wy-crew-gm-edit-title',
  '.wy-crew-col-name',
  '.wy-crew-col-role',
  '.wy-crew-col-location',
  '.wy-crew-col-status',
  '.wy-crew-attr-label',
  '.wy-crew-skill-group-hdr',
  '.wy-cargo-col-name',
  '.wy-cargo-col-qty',
  '.wy-cargo-col-cat',
  '.wy-cc-current-label',
  '.wy-view-nav .wy-nav-status-table .wy-text-dim',
  '.wy-view-comms .wy-data-table .wy-text-dim',
  '.wy-view-status .wy-data-table .wy-text-dim',
  '.wy-view-weapons .wy-text-dim',
  '.wy-view-science .wy-text-dim',
  '.wy-keypad-title',
  '.wy-keypad-subtitle',
  '.wy-clock-rate',
  '.wy-clock-controls-title',
  '.wy-clock-label',
  '.wy-log-form-title',
  '.wy-ss-form-title',
  '.wy-eo-warning',
  '.wy-eo-triggered-by',
  '.wy-eo-sub',
  '.wy-emergency-btn',
  '.wy-eo-cancel-btn',
  '.wy-log-add-btn',
  '.wy-log-view-btn',
  '.wy-log-del-btn',
  '.wy-muthur-send',
  '.wy-scene-btn',
  '.wy-keypad-btn',
  '.wy-toolbar-btn',
  '.wy-clock-action-btn',
  '.wy-scene-back-btn',
  '.wy-scene-push-btn',
  '.wy-scene-refresh-btn',
  '.wy-roster-title',
  '.wy-crew-detail-text',
  '.wy-footer-left > span',
  '.wy-footer-right > span',
  'th',
  '#wy-nav-marker-type option',
  '#wy-timer-category option',
  '#wy-edit-timer-category option',
  '#wy-timer-action option',
  '#wy-timer-system-state option',
  '#wy-crew-status-edit option',
  '#wy-crew-ship-edit option',
  '#wy-cargo-form-category option',
  '#wy-ss-form-type option',
  '#wy-ss-form-classification option',
  '#wy-ss-form-status option',
  '.wy-user-clearance option',
  '.wy-user-role option',
].join(',');

function keyFor(text) {
  return PHRASE_KEYS[text.trim()];
}

export function localizePhrase(text) {
  if (!text || typeof game === 'undefined' || !game.i18n) return text;

  const trimmed = text.trim();
  const key = keyFor(trimmed);
  if (key) return text.replace(trimmed, game.i18n.localize(key));

  if (trimmed.startsWith('ALL SYSTEMS:')) {
    return text.replace('ALL SYSTEMS:', game.i18n.localize('WY_TERMINAL.phrases.allSystems'));
  }

  if (trimmed.endsWith('— SELECT TERMINAL FUNCTION')) {
    return text.replace('— SELECT TERMINAL FUNCTION', game.i18n.localize('WY_TERMINAL.phrases.selectTerminalFunction'));
  }

  for (const [prefix, key] of [
    ['ARMED BY:', 'WY_TERMINAL.emergency.armedBy'],
    ['TRIGGERED BY:', 'WY_TERMINAL.emergency.triggeredBy'],
    ['TARGET:', 'WY_TERMINAL.emergency.target'],
    ['LOCATION:', 'WY_TERMINAL.phrases.locationColon'],
    ['DETECTED SIGNATURES', 'WY_TERMINAL.sections.detectedSignatures'],
  ]) {
    if (trimmed.startsWith(prefix)) return text.replace(prefix, game.i18n.localize(key));
  }

  return text;
}

export function localizeElement(root) {
  if (!root || typeof game === 'undefined' || !game.i18n) return;

  root.querySelectorAll?.(STATIC_UI_SELECTOR).forEach(localizeStaticTextNode);
  if (root.matches?.(STATIC_UI_SELECTOR)) localizeStaticTextNode(root);
}

function localizeStaticTextNode(element) {
  for (const node of element.childNodes) {
    if (node.nodeType !== Node.TEXT_NODE) continue;

    const localized = localizePhrase(node.textContent);
    if (localized !== node.textContent) node.textContent = localized;
  }
}
